import { GetServerSideProps } from 'next';
import Head from 'next/head';
import styles from '../styles/pages/index.module.css';
import { Pokemon } from '@/interfaces/pokemon.interface';

interface HomeProps {
  pokemons: Pokemon[];
}

export default function Home(props: HomeProps) {
  return (
    <div className={styles.main}>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.container}>
        {props.pokemons.slice(0, 20).map((pokemon) => (
          <div key={pokemon.id} className={styles.image}>
            <img
              alt={pokemon.name}
              src={`http://jherr-pokemon.s3.us-west-1.amazonaws.com/${pokemon.image}`}
            />
            <h2>{pokemon.name}</h2>
          </div>
        ))}
      </div>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps<
  Pick<HomeProps, 'pokemons'>
> = async () => {
  const response = await fetch(
    'http://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json'
  );
  const pokemons = (await response.json()) as Pokemon[];

  return { props: { pokemons } };
};
